### ISSUE TITLE
Only ask the user to chose a container when there's more than one

### ISSUE THREAD

**Issue by Mouchoir** [Tignus/AstroSaveConverter#5]
It's useless to ask for the user to chose which container to get the saves from if there's only one container available.
Show this option only if there's 2+ container files were detected

**Comment by Tignus** [comment]
#b6dfff6c8f8fb2ec07f7817b824fc3d1c77694b3

**Comment by Tignus** [comment]
Fixed with b6dfff6c8f8fb2ec07f7817b824fc3d1c77694b3
